language: python
python:
  - "3.4"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libffi-dev
  - sudo apt-get install -y libssl-dev
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover
notifications:
  email:
    - andrei.tataru.metrosystems@gmail.com
